UniversityCourseAndResultManagementSystem/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystem.Manager;
using UniversityCourseAndResultManagementSystem.Models;

namespace UniversityCourseAndResultManagementSystem.Controllers
{

    public class ClassController : Controller
    {
        AllocateClassRoomManager allocateClassRoomManager = new AllocateClassRoomManager();
        DepartmentManager departmentManager = new DepartmentManager();
        CourseManager courseManager = new CourseManager();
        RoomManager roomManager = new RoomManager();
        DayManager dayManager = new DayManager();
        
        public ActionResult Save()
        {
            ViewBag.Departments = GetDepartments();
            ViewBag.Courses = GetCourses();
            ViewBag.Rooms = GetRooms();
            ViewBag.Days = GetDays();
            return View();
        }

        [HttpPost]
        public ActionResult Save(AllocateClassRoom allocateClassRoom)
        {
            ViewBag.Message = allocateClassRoomManager.Save(allocateClassRoom);
            ViewBag.Departments = GetDepartments();
            ViewBag.Courses = GetCourses();
            ViewBag.Rooms = GetRooms();
            ViewBag.Days = GetDays();
            return View();
        }

        private List<Department> GetDepartments()
        {
            return departmentManager.GetDepartments();
        }
        private List<Course> GetCourses()
        {
            return courseManager.GetCourses();
        }

        private List<Room> GetRooms()
        {
            return roomManager.GetRooms();
        }

        private List<Day> GetDays()
        {
            return dayManager.GetDays();
        }

        public JsonResult GetCoursesByDepartmentId(int DepartmentId)
        {
            var courses = GetCourses();
            var courseList = courses.Where(a => a.DepartmentId == DepartmentId).ToList();
            return Json(courseList);
        }
	}
}

UniversityCourseAndResultManagementSystem/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystem.Manager;
using UniversityCourseAndResultManagementSystem.Models;

namespace UniversityCourseAndResultManagementSystem.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/
        CourseManager courseManager = new CourseManager();
        DepartmentManager departmentManager = new DepartmentManager();
        SemesterManager semesterManager = new SemesterManager();
        [HttpGet]
        public ActionResult SaveCourse()
        {
            ViewBag.Departments = departmentManager.GetDepartments();
            ViewBag.Semesters = semesterManager.GetSemesters();
            return View();
        }

        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {
            ViewBag.Message = courseManager.Save(course);
            ViewBag.Departments = departmentManager.GetDepartments();
            ViewBag.Semesters = semesterManager.GetSemesters();
            return View();
        }
        private List<Course> GetCourses()
        {
            return courseManager.GetCourses();
        }

        public JsonResult GetCourseById(int courseId)
        {
            var courses = GetCourses();
            Course course = courses.FirstOrDefault(c => c.CourseId == courseId);
            return Json(course);
        }

        public JsonResult GetCoursesByDepartmentId(int DepartmentId)
        {
            var courses = GetCourses();
            var courseList = courses.Where(a => a.DepartmentId == DepartmentId).ToList();
            return Json(courseList);
        }
	}
}

UniversityCourseAndResultManagementSystem/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystem.Manager;
using UniversityCourseAndResultManagementSystem.Models;

namespace UniversityCourseAndResultManagementSystem.Controllers
{
    public class DepartmentController : Controller
    {
        //
        // GET: /Department/
        DepartmentManager departmentManager = new DepartmentManager();
        public string Save(Department department)
        {
            return departmentManager.Save(department);
        }
        [HttpGet]
        public ActionResult SaveDepartment()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveDepartment(Department department)
        {
            ViewBag.Message = departmentManager.Save(department);
            return View();
        }

        public List<Department> GetDepartments()
        {
            return departmentManager.GetDepartments();
        }

        public ActionResult ShowDepartment()
        {
            List<Department> departments = GetDepartments();
            return View(departments);
        }
	}
}

UniversityCourseAndResultManagementSystem/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementSystem.Manager;
using UniversityCourseAndResultManagementSystem.Models;

namespace UniversityCourseAndResultManagementSystem.Controllers
{
    
    public class TeacherController : Controller
    {

        //
        // GET: /Teacher/

        DesignationManager designationManager = new DesignationManager();
        DepartmentManager departmentManager = new DepartmentManager();
        TeacherManager teacherManager = new TeacherManager();
        CourseManager courseManager = new CourseManager();

        [HttpGet]
        public ActionResult SaveTeacher()
        {
            ViewBag.Departments = departmentManager.GetDepartments();
            ViewBag.Designations = designationManager.GetDesignations();
            return View();
        }
        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            ViewBag.Message = teacherManager.Save(teacher);
            ViewBag.Departments = departmentManager.GetDepartments();
            ViewBag.Designations = designationManager.GetDesignations();
            return View();
        }

        //teacher assign

        public ActionResult AssignCourse()
        {
            ViewBag.Departments = GetDepartments();
            return View();
        }

        [HttpPost]
        public ActionResult AssignCourse(AssignCourse assignCourse)
        {
            ViewBag.Message = courseManager.AssignCourse(assignCourse);
            ViewBag.Departments = GetDepartments();
            return View();
        }

        public JsonResult GetTeachersByDepartmentId(int DepartmentId)
        {
            var teachers = GetTeachers();
            var teacherList = teachers.Where(a => a.DepartmentId == DepartmentId).ToList();
            return Json(teacherList);
        }

        public JsonResult GetTeacherById(int teacherId)
        {
            var teachers = GetTeachers();
            Teacher teacher = teachers.FirstOrDefault(c => c.TeacherId == teacherId);
            teacher.RemainingCredit = teacher.CreditToBeTaken - GetCourseCredit(teacherId);
            
            return Json(teacher);
        }

        private List<Department> GetDepartments()
        {
            return departmentManager.GetDepartments();
        }

        private List<Teacher> GetTeachers()
        {
            return teacherManager.GetTeachers();
        }

        public decimal GetCourseCredit(int teacherId)
        {
            return courseManager.GetCourseCredit(teacherId);
        }
	}
}

UniversityCourseAndResultManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/CSS/myStyle.css" rel="stylesheet"/>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UCRMS", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Save Teacher", "SaveTeacher", "Teacher")</li>
                    <li>@Html.ActionLink("Allocate Class", "Save", "Class")</li>
                    <div class="dropdown">
                        <button class="dropbtn">
                            Course
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-content">
                            <li>@Html.ActionLink("Save course", "SaveCourse", "Course")</li>
                            <li>@Html.ActionLink("Assign Course", "AssignCourse", "Teacher")</li>
                        </div>
                    </div>
                    <div class="dropdown">
                        <button class="dropbtn">
                            Department
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-content">
                            <li>@Html.ActionLink("Save Department", "SaveDepartment", "Department")</li>
                            <li>@Html.ActionLink("Show Department", "ShowDepartment", "Department")</li>
                        </div>
                    </div>
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    <div>
        <br/>
        @RenderBody()
    </div>
   
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/bootstrapjs")
    @RenderSection("scripts", required: false)
</body>
</html>